### ISSUE TITLE
Fornax crashes on build

### ISSUE THREAD

**Issue by oluwandabira** [ionide/Fornax#84]
**Describe the bug**
Fornax crashes when attempting to build a project with error:
```
An unexpected error happend: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 677
   at FSI_0016.Post.generate'(SiteContents ctx, String page)
   at lambda_method17(Closure , Unit , SiteContents , String , String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Generator.EvaluatorHelpers.helper@56(Object next, FSharpList`1 args) in repos/Fornax/src/Fornax/Generator.fs:line 66
   at Generator.EvaluatorHelpers.invokeFunction(Object f, IEnumerable`1 args) in repos/Fornax/src/Fornax/Generator.fs:line 70
   at Generator.GeneratorEvaluator.evaluate@194-1.Invoke(Object generator) in repos/Fornax/src/Fornax/Generator.fs:line 195
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Generator.GeneratorEvaluator.evaluate(FsiEvaluationSession fsi, SiteContents siteContent, String generatorPath, String projectRoot, String page) in repos/Fornax/src/Fornax/Generator.fs:line 190
   at Generator.generate(FsiEvaluationSession fsi, Config cfg, SiteContents siteContent, String projectRoot, String page) in repos/Fornax/src/Fornax/Generator.fs:line 333
   at Generator.action@1-3(String projectRoot, FsiEvaluationSession fsi, Config config, SiteContents sc, String filePath) in repos/Fornax/src/Fornax/Generator.fs:line 496
   at Generator.generateFolder(String projectRoot, Boolean isWatch) in repos/Fornax/src/Fornax/Generator.fs:line 495
   at Fornax.main$cont@185(ArgumentParser`1 parser, FSharpList`1 results, Unit unitVar) in repos/Fornax/src/Fornax/Fornax.fs:line 213
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the Fornax repo
2. Apply the change described in #82
3. Build the repo (`dotnet tool restore`, `dotnet fake build`, `dotnet fake build -t Test`) 
4. Create a new fornax project (`fornax new`)
4. Attempt to build the project (`fornax build`)

**Expected behaviour**
Fornax builds the site.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Ionide version: 5.5.5
 - VSCode version: 1.56.1
 - dotnet SDK version: 5.0.203
 - mono / .Net Framework version:

**Comment by rdipardo** [comment]
The cause of the problem is this exception:
```
System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
```
It's being thrown by `Seq.find` in the post generator script:
 
https://github.com/ionide/Fornax/blob/c9d8b9427669364f49dd4b66ff3fc13b731552d2/src/Fornax.Template/generators/post.fsx#L7-L11

As already observed, this happens ["when sub directories are involved"](https://github.com/ionide/Fornax/issues/82#issuecomment-844086349); specifically, when a Markdown file is detected inside an **ignored** sub directory.

Here's how I reproduced it:

- Follow steps 1-4 as explained by @oluwandabira
- Check the list of ignored directories:

~~~fsharp
// src/Fornax.Template/config.fsx
// ...
let staticPredicate (projectRoot: string, page: string) =
    let ext = Path.GetExtension page
    if page.Contains "_public" ||
       page.Contains "_bin" ||
	// ...
	   ext = ".fsx"
    then
        false
    else
        true
~~~

- Create a Markdown file in one of them (e.g. `_bin`); add the minimum front matter so the `postPredicate` trigger picks it up:

```
	mkdir _bin
	echo -e "--\nlayout: post\n--" > _bin/oops.md
```

- Run `fornax build `

- The build crashes trying to process the ignored file:

~~~
[17:09:24] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\index.html' generated in 848ms
[17:09:25] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\about.html' generated in 544ms
[17:09:25] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\contact.html' generated in 538ms
[17:09:25] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\images/avatar.jpg' generated in 96ms
[17:09:25] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\images/bulma.png' generated in 90ms
[17:09:26] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\images/favicon.png' generated in 112ms
[17:09:26] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\js/sampleJsFile.js' generated in 91ms
[17:09:26] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\posts/post.html' generated in 529ms
[17:09:27] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\posts/post2.html' generated in 540ms
[17:09:27] 'C:\Users\Rob\git\Fornax\src\Fornax.Template\_public\style/style.css' generated in 113ms
An unexpected error happend: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 677
   at FSI_0025.Post.generate'(SiteContents ctx, String page)
   at lambda_method23(Closure , Unit , SiteContents , String , String )
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at FSharp.Quotations.Evaluator.Tools.Invoke@77-1.Invoke(b b, c c)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Generator.EvaluatorHelpers.helper@56(Object next, FSharpList`1 args) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 66
   at Generator.EvaluatorHelpers.invokeFunction(Object f, IEnumerable`1 args) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 70
   at Generator.GeneratorEvaluator.evaluate@194-1.Invoke(Object generator) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 195
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Generator.GeneratorEvaluator.evaluate(FsiEvaluationSession fsi, SiteContents siteContent, String generatorPath, String projectRoot, String page) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 190
   at Generator.generate(FsiEvaluationSession fsi, Config cfg, SiteContents siteContent, String projectRoot, String page) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 333
   at Generator.action@1-3(String projectRoot, FsiEvaluationSession fsi, Config config, SiteContents sc, String filePath) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 496
   at Generator.generateFolder(String projectRoot, Boolean isWatch) in C:\Users\Rob\git\Fornax\src\Fornax\Generator.fs:line 495
   at Fornax.guardedGenerate@226(String cwd, Unit unitVar0) in C:\Users\Rob\source\Fornax\src\Fornax\Fornax.fs:line 228
Finished (TagStatus.Failed) 'TestTemplate' in 00:00:12.3760017
~~~

## Workaround
Edit `generators/post.fsx` to replace `Seq.find` with the safer `Seq.tryFind`. 
You'll have to add some code to satisfy the different type constraints, as in this example here:
https://github.com/rdipardo/Fornax.Seo/blob/670f50440d094c87258b385039d6fef8ba2cfd38/example/Fornax.Seo.Example/generators/post.fsx#L19-L26

**Comment by rdipardo** [comment]
Hey @oluwandabira, and others who might come across this:
the underlying problem with file filtering has been patched: https://github.com/rdipardo/Fornax/commit/d75f7b8f3f4ad021348d059dd09e43bbd62505de
Let me know if it works for you

**Comment by oluwandabira** [comment]
Tested it and I still get the same error.

**Comment by rdipardo** [comment]
### The good news
The `Seq.find` -> `Seq.tryFind` workaround gets the job done on all platforms: https://github.com/rdipardo/Fornax/actions/runs/873339934

### The bad news
The deeper problem with ignored file paths getting into the generator pipeline is platform-dependent.
Tweaking the directory filters works on Windows only : https://github.com/rdipardo/Fornax/actions/runs/873331634

This is consistent with @oluwandabira's results (on Ubuntu 20.04, I assume); and with my own local comparisons:
<details>
<summary>
 PASSED: dotnet 5.0.203 - Windows 10.0.19042 - RID win10-x64
</summary>
<pre>
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax>git remote -v
origin  git@github.com:rdipardo/Fornax.git (fetch)
origin  git@github.com:rdipardo/Fornax.git (push)
upstream        https://github.com/ionide/Fornax (fetch)
upstream        https://github.com/ionide/Fornax (push)

C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax>dir /b
.config
.fake
.github
.gitignore
.paket
.vscode
build.fsx
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Fornax.sln
global.json
LICENSE.md
logo
paket.dependencies
paket.lock
README.md
samples
src
test

C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax>dotnet fake build -t TestTemplate
Starting full restore process.
run TestTemplate
Building project with version: LocalBuild
Shortened DependencyGraph for Target TestTemplate:
<== TestTemplate
   <== Publish
      <== Build
         <== Restore
            <== AssemblyInfo
               <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - AssemblyInfo
Group - 3
  - Restore
Group - 4
  - Build
Group - 5
  - Publish
Group - 6
  - TestTemplate
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0156852
Starting target 'AssemblyInfo'
Finished (Success) 'AssemblyInfo' in 00:00:00.0558696
Starting target 'Restore'
Starting task 'DotNet:restore'
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax> "dotnet.exe"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.8.3.61104
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax> "dotnet.exe"  restore "" /nodeReuse:False "/bl:C:\Users\Rob\AppData\Local\Temp\tmp3763.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\5.0.104\MSBuild.dll -nologo -maxcpucount -target:Restore -verbosity:m /bl:C:\Users\Rob\AppData\Local\Temp\tmp3763.tmp.binlog /nodeReuse:False .\Fornax.sln
  Determining projects to restore...
  Paket version 5.257.0
  Starting restore process.
  Performance:
   - Runtime: 1 second
  Restored C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\test\Fornax.Core.UnitTests\Fornax.Core.UnitTests.fsproj (in 336 ms).
  Restored C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Core\Fornax.Core.fsproj (in 336 ms).
  Restored C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax\Fornax.fsproj (in 1.03 sec).
Finished (Success) 'DotNet:restore' in 00:00:08.5763596
Finished (Success) 'Restore' in 00:00:08.5839909
Starting target 'Build'
Starting task 'DotNet:build'
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax> "dotnet.exe"  build "" --configuration Release /nodeReuse:False "/bl:C:\Users\Rob\AppData\Local\Temp\tmp5879.tmp.binlog" (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.104\MSBuild.dll -consoleloggerparameters:Summary -maxcpucount -property:Configuration=Release -restore -verbosity:m /bl:C:\Users\Rob\AppData\Local\Temp\tmp5879.tmp.binlog /nodeReuse:False .\Fornax.sln
  Determining projects to restore...
  All projects are up-to-date for restore.
  Fornax.Core -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Core\bin\Release\netstandard2.0\Fornax.Core.dll
  Fornax.Core.UnitTests -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\test\Fornax.Core.UnitTests\bin\Release\net5.0\Fornax.Core.UnitTests.dll
  Fornax -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax\bin\Release\net5.0\Fornax.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:22.03
Finished (Success) 'DotNet:build' in 00:00:23.3502911
Finished (Success) 'Build' in 00:00:23.3535331
Starting target 'Publish'
Starting task 'DotNet:publish': src/Fornax
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax> "dotnet.exe"  publish src/Fornax --configuration Release --output "C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\temp" /nodeReuse:False "/bl:C:\Users\Rob\AppData\Local\Temp\tmpB3B9.tmp.binlog" (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.104\MSBuild.dll -maxcpucount -property:Configuration=Release -property:PublishDir=C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\temp -restore -target:Publish -verbosity:m /bl:C:\Users\Rob\AppData\Local\Temp\tmpB3B9.tmp.binlog /nodeReuse:False src/Fornax\Fornax.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  Fornax.Core -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Core\bin\Release\netstandard2.0\Fornax.Core.dll
  Fornax -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax\bin\Release\net5.0\Fornax.dll
  Fornax -> C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\temp\
Finished (Success) 'DotNet:publish' in 00:00:04.4845510
Finished (Success) 'Publish' in 00:00:04.4875068
Starting target 'TestTemplate'
templateDir: C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src/Fornax.Template/
C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src/Fornax.Template/> "dotnet" "C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\temp\Fornax.dll" watch (In: false, Out: false, Err: false)
[20:53:28] multiple files generated in 763ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\about.html' generated in 429ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\contact.html' generated in 409ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\images/avatar.jpg' generated in 102ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\images/bulma.png' generated in 1ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\images/favicon.png' generated in 0ms
[20:53:29] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\js/sampleJsFile.js' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post.html' generated in 417ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post2.html' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post3.html' generated in 3ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post4.html' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post5.html' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/post6.html' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\style/style.css' generated in 1ms
[20:53:30] 'C:\Users\Rob\source\repos\workspace\git\dotnet\Fornax\src\Fornax.Template\_public\posts/subdir/post3.html' generated in 1ms
Generation time: 00:00:10.4731909
[20:53:30] Watch mode started. Press any key to exit.
[20:53:30 INF] Smooth! Suave listener started in 75.094ms with binding 127.0.0.1:8080
qExiting...
Finished (Success) 'TestTemplate' in 00:00:37.9183656

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0049051
AssemblyInfo   00:00:00.0549984
Restore        00:00:08.5830416
Build          00:00:23.3523244
Publish        00:00:04.4865412
TestTemplate   00:00:37.9171431
Total:         00:01:14.6369439
Status:        Ok
---------------------------------------------------------------------
Performance:
 - Cli parsing: 469 milliseconds
 - Packages: 1 second
   - Creating Runtime Graph: 146 milliseconds
   - Retrieve Assembly List: 1 second
 - Script compiling: 8 seconds
 - Script analyzing: 1 second
 - Script running: 1 minute, 15 seconds
 - Script cleanup: 14 milliseconds
 - Runtime: 1 minute, 28 seconds
</pre>
</details>

<details>
<summary>
 FAILED: dotnet 5.0.203 - bunsenlabs (i.e. Debian 10.5) - RID linux-x64 - with extra debug output to show directory paths
</summary>
<pre>
rob@bunsen:~/dev/Fornax (fix/#84 *<>)
$ git remote -v
origin	git@github.com:rdipardo/Fornax.git (fetch)
origin	git@github.com:rdipardo/Fornax.git (push)
upstream	https://github.com/ionide/Fornax.git (fetch)
upstream	https://github.com/ionide/Fornax.git (push)
rob@bunsen:~/dev/Fornax (fix/#84 *<>)
$ ls -l
total 348
-rw-r--r--  1 rob rob   7811 May 19 17:36 build.fsx
-rw-r--r--  1 rob rob   1947 May 19 17:36 CHANGELOG.md
-rw-r--r--  1 rob rob   3358 May 19 17:36 CODE_OF_CONDUCT.md
-rw-r--r--  1 rob rob   5794 May 19 17:36 CONTRIBUTING.md
-rw-r--r--  1 rob rob   4491 May 19 17:36 Fornax.sln
-rw-r--r--  1 rob rob     79 May 24 20:07 global.json
-rw-r--r--  1 rob rob   1080 May 19 17:36 LICENSE.md
drwxr-xr-x  2 rob rob   4096 May 19 17:36 logo
drwxr-xr-x  2 rob rob   4096 May 24 20:47 out
-rw-r--r--  1 rob rob    647 May 19 17:36 paket.dependencies
drwxr-xr-x  2 rob rob   4096 May 24 20:48 paket-files
-rw-r--r--  1 rob rob 266347 May 19 17:36 paket.lock
-rw-r--r--  1 rob rob  10213 May 24 20:05 README.md
drwxr-xr-x  8 rob rob   4096 May 19 17:36 samples
drwxr-xr-x  5 rob rob   4096 May 19 17:36 src
drwxr-xr-x 17 rob rob   4096 May 24 20:49 temp
drwxr-xr-x  3 rob rob   4096 May 19 17:36 test
rob@bunsen:~/dev/Fornax (fix/#84 *<>)
$ dotnet fake build -t TestTemplate
The last restore is still up to date. Nothing left to do.
run TestTemplate
Building project with version: LocalBuild
Shortened DependencyGraph for Target TestTemplate:
<== TestTemplate
   <== Publish
      <== Build
         <== Restore
            <== AssemblyInfo
               <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - AssemblyInfo
Group - 3
  - Restore
Group - 4
  - Build
Group - 5
  - Publish
Group - 6
  - TestTemplate
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0692428
Starting target 'AssemblyInfo'
Finished (Success) 'AssemblyInfo' in 00:00:00.0838182
Starting target 'Restore'
Starting task 'DotNet:restore'
> "/usr/bin/mono" --version (In: false, Out: true, Err: true)
/home/rob/dev/Fornax> "dotnet"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.9.0.11203
/home/rob/dev/Fornax> "dotnet"  restore "" /bl:/tmp/tmpAP83QE.tmp.binlog (In: false, Out: false, Err: false)
/usr/share/dotnet/sdk/5.0.203/MSBuild.dll -nologo -maxcpucount -target:Restore -verbosity:m /bl:/tmp/tmpAP83QE.tmp.binlog ./Fornax.sln
  Determining projects to restore...
  Restored /home/rob/dev/Fornax/test/Fornax.Core.UnitTests/Fornax.Core.UnitTests.fsproj (in 1 sec).
  Restored /home/rob/dev/Fornax/src/Fornax.Core/Fornax.Core.fsproj (in 1 sec).
  Restored /home/rob/dev/Fornax/src/Fornax/Fornax.fsproj (in 1.29 sec).
Finished (Success) 'DotNet:restore' in 00:00:11.8869072
Finished (Success) 'Restore' in 00:00:11.9007670
Starting target 'Build'
Starting task 'DotNet:build'
/home/rob/dev/Fornax> "dotnet"  build "" --configuration Release /bl:/tmp/tmpOsWrWe.tmp.binlog (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/5.0.203/MSBuild.dll -consoleloggerparameters:Summary -maxcpucount -property:Configuration=Release -restore -verbosity:m /bl:/tmp/tmpOsWrWe.tmp.binlog ./Fornax.sln
  Determining projects to restore...
  All projects are up-to-date for restore.
  Fornax.Core -> /home/rob/dev/Fornax/src/Fornax.Core/bin/Release/netstandard2.0/Fornax.Core.dll
  Fornax.Core.UnitTests -> /home/rob/dev/Fornax/test/Fornax.Core.UnitTests/bin/Release/net5.0/Fornax.Core.UnitTests.dll
  Fornax -> /home/rob/dev/Fornax/src/Fornax/bin/Release/net5.0/Fornax.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:54.42
Finished (Success) 'DotNet:build' in 00:00:56.6001636
Finished (Success) 'Build' in 00:00:56.6104510
Starting target 'Publish'
Starting task 'DotNet:publish': src/Fornax
/home/rob/dev/Fornax> "dotnet"  publish src/Fornax --configuration Release --output /home/rob/dev/Fornax/temp /bl:/tmp/tmpZTRkIO.tmp.binlog (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/5.0.203/MSBuild.dll -maxcpucount -property:Configuration=Release -property:PublishDir=/home/rob/dev/Fornax/temp -restore -target:Publish -verbosity:m /bl:/tmp/tmpZTRkIO.tmp.binlog src/Fornax/Fornax.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  Fornax.Core -> /home/rob/dev/Fornax/src/Fornax.Core/bin/Release/netstandard2.0/Fornax.Core.dll
  Fornax -> /home/rob/dev/Fornax/src/Fornax/bin/Release/net5.0/Fornax.dll
  Fornax -> /home/rob/dev/Fornax/temp/
Finished (Success) 'DotNet:publish' in 00:00:12.0238785
Finished (Success) 'Publish' in 00:00:12.0293208
Starting target 'TestTemplate'
templateDir: /home/rob/dev/Fornax/src/Fornax.Template/
/home/rob/dev/Fornax/src/Fornax.Template/> "dotnet" /home/rob/dev/Fornax/temp/Fornax.dll watch (In: false, Out: false, Err: false)
[20:55:52] multiple files generated in 509ms
[20:55:53] '/home/rob/dev/Fornax/src/Fornax.Template/_public/about.html' generated in 635ms
[20:55:54] '/home/rob/dev/Fornax/src/Fornax.Template/_public/contact.html' generated in 608ms
Rel path is
Rel path is posts
Rel path is posts
Rel path is posts
Rel path is posts
Rel path is posts
Rel path is posts
Rel path is loaders
Rel path is loaders
Rel path is loaders
Rel path is generators
Rel path is generators
Rel path is generators
Rel path is generators
Rel path is generators
Rel path is generators
Rel path is js
Rel path is images
Rel path is images
Rel path is images
Rel path is _lib
Rel path is _lib
Rel path is _public
Rel path is _public
Rel path is _public
Rel path is style
Rel path is posts/subdir
Rel path is _public/posts
Generating /home/rob/dev/Fornax/src/Fornax.Template/config.fsx
Generating /home/rob/dev/Fornax/src/Fornax.Template/posts/post6.md
An unexpected error happend: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 677
   at FSI_0022.Post.generate'(SiteContents ctx, String page)
   at lambda_method21(Closure , Unit , SiteContents , String , String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Generator.EvaluatorHelpers.helper@56(Object next, FSharpList`1 args) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 66
   at Generator.EvaluatorHelpers.invokeFunction(Object f, IEnumerable`1 args) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 70
   at Generator.GeneratorEvaluator.evaluate@194-1.Invoke(Object generator) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 195
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at Generator.GeneratorEvaluator.evaluate(FsiEvaluationSession fsi, SiteContents siteContent, String generatorPath, String projectRoot, String page) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 190
   at Generator.generate(FsiEvaluationSession fsi, Config cfg, SiteContents siteContent, String projectRoot, String page) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 333
   at Generator.action@1-3(FSharpFunc`2 relative, String projectRoot, FsiEvaluationSession fsi, Config config, SiteContents sc, String filePath) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 502
   at Generator.generateFolder(String projectRoot, Boolean isWatch) in /home/rob/dev/Fornax/src/Fornax/Generator.fs:line 500
   at Fornax.guardedGenerate@226(String cwd, Unit unitVar0) in /home/rob/dev/Fornax/src/Fornax/Fornax.fs:line 228
Finished (Failed) 'TestTemplate' in 00:00:23.4308125

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0534042
AssemblyInfo   00:00:00.0835117
Restore        00:00:11.9005128
Build          00:00:56.6101713
Publish        00:00:12.0287613
TestTemplate   00:00:23.4298762   (Error while running 'dotnet' with args: /home/rob/dev/Fornax/temp/Fornax.dll watch)
Total:         00:01:44.5321666
Status:        Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'TestTemplate' failed.
-> One or more errors occurred. (Error while running 'dotnet' with args: /home/rob/dev/Fornax/temp/Fornax.dll watch)
-> Error while running 'dotnet' with args: /home/rob/dev/Fornax/temp/Fornax.dll watch
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Performance:
 - Cli parsing: 795 milliseconds
 - Packages: 215 milliseconds
 - Script compiling: 19 seconds
 - Script analyzing: 65 milliseconds
 - Script running: 1 minute, 45 seconds
 - Script cleanup: 91 milliseconds
 - Runtime: 2 minutes, 7 seconds
 </pre>
</details>

**Comment by oluwandabira** [comment]
So the underlying issue still seems to be with ignored file paths?

**Comment by rdipardo** [comment]
Not all file paths, just Markdown files that get sent to `generators/post.fsx`. 
I can't find any other code path that could result in `KeyNotFoundException` besides this call to `Seq.find`:

https://github.com/ionide/Fornax/blob/5902c57f42ced02d9c825bb7a6a41543499cc88a/src/Fornax.Template/generators/post.fsx#L7-L11

My guess is that files from ignored paths like `_public/`, are getting passed in as `page`, and the match fails because `SiteContents` only collects valid files.

I see there's no answer yet to #87, but I wouldn't expect the Generator to pick up this kind of error; it's only watching for the 
`FornaxGeneratorException` type:

https://github.com/ionide/Fornax/blob/5902c57f42ced02d9c825bb7a6a41543499cc88a/src/Fornax/Fornax.fs#L216-L221

Exceptions throw by generator scripts are emitted by FSI and not handled as far as I know.

So, for now, if you just want a working generator, the quickest way is switching `Seq.find` with `Seq.tryFind` like this: https://github.com/rdipardo/Fornax/commit/cbabae075e6c50b4c01f7b18ab37b01e4414ced8

If you want a generator that builds, but crashes in watch mode, apply the patch at https://github.com/rdipardo/Fornax/commit/6afb2be29b4f123dfd40e7de9f33226b8f540553
